version: '3.8'

services:
  scanner:
    build: .
    container_name: warder-tx-scanner
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env:ro
    networks:
      - warder-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  warder-network:
    driver: bridge